version: "3.7"

x-images:
  django: &django
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
      target: dev
    user: ${UID:-1000}:${GID:-1000}
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
    env_file:
      - db.env
      - app.env
    volumes:
      - .:/opt/terra-visu


services:
  db:
    image: postgis/postgis:15-3.3
    env_file:
      - db.env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
  
  web:
    <<: [ *django ]
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
      - redis
      - celery

  celery:
    <<: [ *django ]
    command: celery -A project worker -c 1 -l debug -E
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    volumes:
      - .:/app

volumes:
  db:
  redis:
