version: "3.7"
services:
  db:
    image: postgis/postgis:15-3.3
    env_file:
      - db.env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
      target: dev
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - db.env
      - app.env
    volumes:
      - .:/opt/terra-visu
    depends_on:
      - db

volumes:
  db: