name: Linting

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  flake8:
    name: Python code styling
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip3 install flake8

      - name: Flake8
        run: |
          flake8 project

  isort:
    name: Python code import sorting
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip3 install isort

      - name: Isort
        run: |
          isort -c project

  black:
    name: Black checking
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip3 install black

      - name: Black
        run: |
          black --check project
